# -*- coding: utf-8 -*-
"""
/***************************************************************************
 MonetDBeConnector
                                 A QGIS plugin
 MonetDBeConnector
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2021-09-27
        copyright            : (C) 2021 by MonetDBSolutions
        email                : info@monetdb.org
        git sha              : $Format:%H$
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load MonetDBeConnector class from file MonetDBeConnector.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .MonetDBeConnector import MonetDBeConnector
    return MonetDBeConnector(iface)
